# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2018

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: 'atom.xml'

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  About: /about/
  Links: /links/
  Resources: /resources/
  Tools: /tools/
  #Tags: /tags/
  #Categories: /categories/

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

# LaTeX support (via MathJax)
latex: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: YXV0dW1ubG8udkBvdXRsb29rLmNvbQo=
  stack-overflow:
  twitter: https://twitter.com/d0zingcat
  facebook:
  linkedin:
  google:
  github: https://github.com/d0zingcat
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: #7kYxzYmBVmID1jjDBItOSLma-gzGzoHsz
  app_key: #AmXKyQD0B1jF40Sa27wmq72D

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-92083861-2
# Google Verification
google_verification:

# Disqus
disqus_shortname: endlessloop

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
# Demo: https://gitalk.github.io
# https://github.com/gitalk/gitalk
gitalk:
  enable: false
  github_id: d0zingcat
  repo: infloop.life
  client_id: 8b3b0672f88ca539fdd7
  client_secret: ecf61aaa314e62240f94529656b98eca04fe8d94
  admin_user: d0zingcat
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language: en, zh-CN

# ===========================================
# Version
# ===========================================
version: 2.11.0
